# Generated by Django 4.2.13 on 2024-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(choices=[('Retiro', 'Retiro'), ('San Nicolás', 'San Nicolás'), ('Puerto Madero', 'Puerto Madero'), ('San Telmo', 'San Telmo'), ('Montserrat', 'Montserrat'), ('Constitución', 'Constitución'), ('Recoleta', 'Recoleta'), ('Balvanera', 'Balvanera'), ('San Cristóbal', 'San Cristóbal'), ('La Boca', 'La Boca'), ('Barracas', 'Barracas'), ('Parque Patricios', 'Parque Patricios'), ('Nueva Pompeya', 'Nueva Pompeya'), ('Almagro', 'Almagro'), ('Boedo', 'Boedo'), ('Caballito', 'Caballito'), ('Flores', 'Flores'), ('Parque Chacabuco', 'Parque Chacabuco'), ('Villa Soldati', 'Villa Soldati'), ('Villa Riachuelo', 'Villa Riachuelo'), ('Villa Lugano', 'Villa Lugano'), ('Liniers', 'Liniers'), ('Mataderos', 'Mataderos'), ('Parque Avellaneda', 'Parque Avellaneda'), ('Villa Real', 'Villa Real'), ('Monte Castro', 'Monte Castro'), ('Versalles', 'Versalles'), ('Floresta', 'Floresta'), ('Vélez Sarsfield', 'Vélez Sarsfield'), ('Villa Luro', 'Villa Luro'), ('Villa General Mitre', 'Villa General Mitre'), ('Villa Devoto', 'Villa Devoto'), ('Villa del Parque', 'Villa del Parque'), ('Villa Santa Rita', 'Villa Santa Rita'), ('Coghlan', 'Coghlan'), ('Saavedra', 'Saavedra'), ('Villa Urquiza', 'Villa Urquiza'), ('Villa Pueyrredón', 'Villa Pueyrredón'), ('Núñez', 'Núñez'), ('Belgrano', 'Belgrano'), ('Colegiales', 'Colegiales'), ('Palermo', 'Palermo'), ('Chacarita', 'Chacarita'), ('Villa Crespo', 'Villa Crespo'), ('La Paternal', 'La Paternal'), ('Villa Ortúzar', 'Villa Ortúzar'), ('Agronomía', 'Agronomía'), ('Parque Chas', 'Parque Chas')], max_length=50)),
                ('commune', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], editable=False)),
                ('category', models.CharField(choices=[('Chocolatería y Pastelería', 'Chocolatería y Pastelería'), ('Confitería y Café', 'Confitería y Café'), ('Confitería y Pan Tradicional', 'Confitería y Pan Tradicional'), ('Patisserie y Boulangerie', 'Patisserie y Boulangerie')], max_length=50)),
                ('local_type', models.CharField(choices=[('Cafetería', 'Cafetería'), ('Chocolatería', 'Chocolatería'), ('Crepería', 'Crepería'), ('Delicatessen', 'Delicatessen'), ('Panadería', 'Panadería'), ('Panadería Francesa', 'Panadería Francesa'), ('Pastelería', 'Pastelería'), ('Pastelería especializada en tartas nupciales', 'Pastelería especializada en tartas nupciales'), ('Pastelería francesa', 'Pastelería francesa'), ('Repostería', 'Repostería')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('maps', models.URLField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
